<?php

/**
 * DmAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmAreaTable extends PluginDmAreaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return DmAreaTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmArea');
    }
}