<?php

/**
 * DmBehaviorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmBehaviorTable extends PluginDmBehaviorTable
{
    /**
     * Returns an instance of this class.
     *
     * @return DmBehaviorTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmBehavior');
    }
}