<?php

/**
 * DmCatalogueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmCatalogueTable extends PluginDmCatalogueTable
{
    /**
     * Returns an instance of this class.
     *
     * @return DmCatalogueTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmCatalogue');
    }
}