<?php

/**
 * DmSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmSettingTable extends PluginDmSettingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return DmSettingTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmSetting');
    }
}