<?php

/**
 * DmTransUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmTransUnitTable extends PluginDmTransUnitTable
{
    /**
     * Returns an instance of this class.
     *
     * @return DmTransUnitTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmTransUnit');
    }
}