<?php

/**
 * dmBitLyUrlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class dmBitLyUrlTable extends PlugindmBitLyUrlTable
{
    /**
     * Returns an instance of this class.
     *
     * @return dmBitLyUrlTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('dmBitLyUrl');
    }
}