<?php

/**
 * BasedmBitLyUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $short
 * @property string $expanded
 * 
 * @method string     getShort()    Returns the current record's "short" value
 * @method string     getExpanded() Returns the current record's "expanded" value
 * @method dmBitLyUrl setShort()    Sets the current record's "short" value
 * @method dmBitLyUrl setExpanded() Sets the current record's "expanded" value
 * 
 * @package    viveSmart
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasedmBitLyUrl extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dm_bit_ly_url');
        $this->hasColumn('short', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 32,
             ));
        $this->hasColumn('expanded', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}