<?php

/**
 * DmRecordPermissionAssociationGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmRecordPermissionAssociationGroupTable extends PluginDmRecordPermissionAssociationGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return DmRecordPermissionAssociationGroupTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmRecordPermissionAssociationGroup');
    }
}