<?php

/**
 * DmRecordPermissionAssociationUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmRecordPermissionAssociationUserTable extends PluginDmRecordPermissionAssociationUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return DmRecordPermissionAssociationUserTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmRecordPermissionAssociationUser');
    }
}